# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


list() 在轉換的時候只會將第一維的陣列轉換成list的格式。<br>
但用tolist()轉換時就可以將所陣列資料轉換成list的格式。



### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [1]:
import numpy as np

a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 

In [2]:
a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[8 8 6 1 7 3]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [3]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[0 2 9 3]
 [9 7 7 3]
 [5 3 0 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [4]:
c = np.random.randint(10, size=(2,3,2))

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[6 1]
  [3 3]
  [3 7]]

 [[0 0]
  [4 7]
  [7 5]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [5]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[8, 4, 1, 4, 6, 4]
[8, 4, 1, 4, 6, 4]


In [6]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[7, 2, 4, 2], [5, 8, 0, 9], [8, 6, 9, 6]]
[array([7, 2, 4, 2]), array([5, 8, 0, 9]), array([8, 6, 9, 6])]


In [7]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[[[6, 2], [6, 6], [7, 3]], [[2, 0], [7, 1], [6, 3]]]
[array([[6, 2],
       [6, 6],
       [7, 3]]), array([[2, 0],
       [7, 1],
       [6, 3]])]


In [8]:
#basic
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    nlist=[]
    for a in iterable:
        nlist.append(tolist(a))
    return nlist

print(tolist(a))
print(tolist(b))
print(tolist(c))

[8, 4, 1, 4, 6, 4]
[[7, 2, 4, 2], [5, 8, 0, 9], [8, 6, 9, 6]]
[[[6, 2], [6, 6], [7, 3]], [[2, 0], [7, 1], [6, 3]]]


In [9]:
#advanced
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[8, 4, 1, 4, 6, 4]
[[7, 2, 4, 2], [5, 8, 0, 9], [8, 6, 9, 6]]
[[[6, 2], [6, 6], [7, 3]], [[2, 0], [7, 1], [6, 3]]]
