# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [31]:
# 記得先 Import 正確的套件
import numpy as np
a = np.arange(11)
a[3:7] *= -1
print(a)

[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [35]:
A = np.random.rand(3, 6)
print(A)
print((np.where(A>0.5))[0].size)
ans = len(A[A>0.5])
print(ans)

[[0.96145055 0.05263858 0.46812409 0.89757345 0.87385539 0.04659128]
 [0.55530425 0.60912998 0.38195616 0.67054601 0.97016205 0.69581616]
 [0.72541511 0.36842503 0.05116304 0.90399112 0.83217648 0.53426216]]
12
12
