# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



### 答：在使用上沒有太大的區別。

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [9]:
import numpy as np

A = np.random.random((5, 5))

A = (A-A.min())/(A.max()-A.min())
print(A)

[[0.01568121 0.72916374 0.07978182 0.94770472 0.98972368]
 [0.60349113 0.51498467 0.58991468 0.76114676 0.70790001]
 [0.03775694 0.36615032 0.56590628 1.         0.44822313]
 [0.         0.03076385 0.129434   0.94690576 0.54334847]
 [0.15621574 0.424622   0.60221863 0.84619279 0.49968885]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [16]:
T = np.random.random(10)
T[T.argmax()] = -1
print(T)

[0.77820512 0.71549912 0.41235829 0.38970755 0.74549147 0.34878031
 0.42333134 0.78471344 0.7916748  0.28376174]
[ 0.77820512  0.71549912  0.41235829  0.38970755  0.74549147  0.34878031
  0.42333134  0.78471344 -1.          0.28376174]
