# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

In [1]:
import numpy as np

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [2]:
a = np.arange(10)

In [3]:
print(a.sum())
print("回傳所有數值相加的結果")

45
回傳所有數值相加的結果


In [4]:
print(np.sum(a))
print("回傳所有數值相加的結果")

45
回傳所有數值相加的結果


In [5]:
print(sum(a)) 
print("回傳第0軸相加的結果")

45
回傳第0軸相加的結果


2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [6]:
A = np.random.random((5, 5))
print(A)
A_min, A_max = A.min(),A.max()
A = (A - A_min) / (A_max - A_min)

print(A)

[[0.98189335 0.01905926 0.29684133 0.17441882 0.03771859]
 [0.88031818 0.18672851 0.31692489 0.896694   0.17725224]
 [0.70045907 0.31353436 0.57846491 0.71986922 0.00596585]
 [0.64751806 0.28335922 0.42837302 0.62160092 0.39364838]
 [0.49702164 0.59868665 0.23618769 0.19736875 0.20750804]]
[[1.         0.01341638 0.29805029 0.17260808 0.03253596]
 [0.89591935 0.1852214  0.31862924 0.9126991  0.17551139]
 [0.71162379 0.31515508 0.58662048 0.73151271 0.        ]
 [0.65737691 0.28423563 0.43282639 0.63082049 0.39724522]
 [0.50316831 0.60734102 0.23590056 0.1961241  0.20651348]]


3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [16]:
B = np.random.randint(1,10,size=10)
print(B)
print(B.max())

B[B==(B.max())] = -1

[4 3 7 4 7 6 5 5 5 4]
7
