# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
# 記得先 Import 正確的套件
import numpy as np
import timeit as tt

In [2]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
print(Z)

[[[7 3 6 ... 6 8 4]
  [5 8 7 ... 7 2 6]
  [0 5 0 ... 5 7 4]
  ...
  [2 5 1 ... 9 2 8]
  [9 6 7 ... 5 7 4]
  [9 1 6 ... 1 5 3]]

 [[1 7 8 ... 1 0 5]
  [3 9 8 ... 4 5 7]
  [3 2 9 ... 1 3 7]
  ...
  [3 6 2 ... 9 0 8]
  [6 7 9 ... 6 7 7]
  [3 1 6 ... 1 3 6]]

 [[3 1 5 ... 2 1 2]
  [8 9 8 ... 5 7 0]
  [7 3 7 ... 7 9 6]
  ...
  [2 0 3 ... 5 0 5]
  [8 3 9 ... 5 1 8]
  [0 7 8 ... 0 1 7]]

 ...

 [[4 4 7 ... 2 9 0]
  [1 7 8 ... 5 6 0]
  [7 1 0 ... 2 8 5]
  ...
  [3 2 2 ... 0 9 4]
  [2 1 6 ... 1 1 1]
  [1 9 8 ... 7 9 7]]

 [[8 7 9 ... 7 4 0]
  [4 7 5 ... 2 8 9]
  [1 6 6 ... 6 2 5]
  ...
  [5 2 3 ... 2 2 0]
  [1 7 3 ... 5 1 2]
  [5 4 4 ... 3 1 7]]

 [[9 0 0 ... 6 5 4]
  [6 3 6 ... 3 8 8]
  [7 9 5 ... 5 0 5]
  ...
  [8 1 1 ... 1 1 5]
  [7 8 3 ... 5 5 3]
  [7 2 3 ... 6 8 6]]]


In [6]:
%timeit -n 10 a =2

UnboundLocalError: local variable 'Z' referenced before assignment

In [4]:
tt.timeit('text.find(char)', setup='text = "sample string"; char = "g"')

0.21516915699999117

### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [5]:

Z = np.random.randint(0,10,50)
print(Z)


[8 7 2 4 3 4 2 3 6 3 5 5 2 2 2 1 9 1 9 4 2 1 5 5 4 8 8 1 6 0 4 0 1 4 2 7 0
 1 2 0 9 7 9 1 4 5 7 4 2 6]


In [6]:
'''
Your Code
'''

'\nYour Code\n'

In [7]:
'''
Your Code
'''

'\nYour Code\n'

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [8]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[9, 1, 8, 0, 9, 3]
[9, 1, 8, 0, 9, 3]
[[3, 6, 1, 4], [2, 2, 7, 7], [6, 1, 3, 4]]
[array([3, 6, 1, 4]), array([2, 2, 7, 7]), array([6, 1, 3, 4])]
[[[9, 6], [2, 4], [0, 0]], [[5, 3], [4, 7], [2, 3]]]
[array([[9, 6],
       [2, 4],
       [0, 0]]), array([[5, 3],
       [4, 7],
       [2, 3]])]


In [9]:
'''
Your Code
'''

'\nYour Code\n'